/** 高校 id → 主域名（非 id.edu.cn 的特殊映射） */
export const UNIVERSITY_DOMAIN_OVERRIDES = {
  tsinghua: 'tsinghua.edu.cn',
  pku: 'pku.edu.cn',
  zju: 'zju.edu.cn',
  sjtu: 'sjtu.edu.cn',
  fudan: 'fudan.edu.cn',
  nju: 'nju.edu.cn',
  ustc: 'ustc.edu.cn',
  whu: 'whu.edu.cn',
  hit: 'hit.edu.cn',
  xjt: 'xjtu.edu.cn',
  sysu: 'sysu.edu.cn',
  tongji: 'tongji.edu.cn',
  hust: 'hust.edu.cn',
  tju: 'tju.edu.cn',
  scut: 'scut.edu.cn',
  seu: 'seu.edu.cn',
  buaa: 'buaa.edu.cn',
  bit: 'bit.edu.cn',
  scu: 'scu.edu.cn',
  ruc: 'ruc.edu.cn',
  sdu: 'sdu.edu.cn',
  csu: 'csu.edu.cn',
  dlut: 'dlut.edu.cn',
  jlu: 'jlu.edu.cn',
  xmu: 'xmu.edu.cn',
  ecnu: 'ecnu.edu.cn',
  cau: 'cau.edu.cn',
  nwpu: 'nwpu.edu.cn',
  lzu: 'lzu.edu.cn',
  cqu: 'cqu.edu.cn',
  ouc: 'ouc.edu.cn',
  hnu: 'hnu.edu.cn',
  nudt: 'nudt.edu.cn',
  uestc: 'uestc.edu.cn',
  bnu: 'bnu.edu.cn',
  nwafu: 'nwafu.edu.cn',
  njust: 'njust.edu.cn',
  nuaa: 'nuaa.edu.cn',
  swjtu: 'swjtu.edu.cn',
  swu: 'swu.edu.cn',
  whut: 'whut.edu.cn',
  cug: 'cug.edu.cn',
  cugb: 'cugb.edu.cn',
  cumt: 'cumt.edu.cn',
  cumtb: 'cumtb.edu.cn',
  cug2: 'cug.edu.cn',
  cup: 'cup.edu.cn',
  cuc: 'cuc.edu.cn',
  cufe: 'cufe.edu.cn',
  uibe: 'uibe.edu.cn',
  bfsu: 'bfsu.edu.cn',
  muc: 'muc.edu.cn',
  nankai: 'nankai.edu.cn',
  tianjin: 'tju.edu.cn',
  hebut: 'hebut.edu.cn',
  tyut: 'tyut.edu.cn',
  imu: 'imu.edu.cn',
  lnu: 'lnu.edu.cn',
  dmu: 'dmu.edu.cn',
  nenu: 'nenu.edu.cn',
  neu: 'neu.edu.cn',
  hrbeu: 'hrbeu.edu.cn',
  nefu: 'nefu.edu.cn',
  ecust: 'ecust.edu.cn',
  shufe: 'shufe.edu.cn',
  shisu: 'shisu.edu.cn',
  shu: 'shu.edu.cn',
  suda: 'suda.edu.cn',
  hhu: 'hhu.edu.cn',
  jnu: 'jnu.edu.cn',
  njfu: 'njfu.edu.cn',
  njau: 'njau.edu.cn',
  cpu: 'cpu.edu.cn',
  nwu: 'nwu.edu.cn',
  hznu: 'hznu.edu.cn',
  zafu: 'zafu.edu.cn',
  ahnu: 'ahnu.edu.cn',
  hfut: 'hfut.edu.cn',
  fzu: 'fzu.edu.cn',
  ncu: 'ncu.edu.cn',
  sdnu: 'sdnu.edu.cn',
  zzu: 'zzu.edu.cn',
  ccnu: 'ccnu.edu.cn',
  hzau: 'hzau.edu.cn',
  hnnu: 'hnnu.edu.cn',
  scnu: 'scnu.edu.cn',
  gxu: 'gxu.edu.cn',
  hainanu: 'hainanu.edu.cn',
  swufe: 'swufe.edu.cn',
  ynu: 'ynu.edu.cn',
  gzu: 'gzu.edu.cn',
  nxu: 'nxu.edu.cn',
  qhu: 'qhu.edu.cn',
  xju: 'xju.edu.cn',
  bupt: 'bupt.edu.cn',
  bjtu: 'bjtu.edu.cn',
  pkuhsc: 'bjmu.edu.cn',
  jnu2: 'jnu.edu.cn',
  cnu: 'cnnu.edu.cn',
  bistu: 'bistu.edu.cn',
}

export const UNIVERSITY_TALENT_PATHS = [
  '/17158/list.htm',
  '/gjjcqnkxjjhdz/list.htm',
  '/gjjcqnjjhdz/list.htm',
  '/gjjcqnjjhdz/list1.htm',
  '/gjjcqnjjhdz/list2.htm',
  '/gjjcqnjjhdz_Al.htm',
  '/gjjcqnjjhdz/list.psp',
  '/rczp/info/1027/5210.htm',
  '/28176/list.htm',
  '/28176/list2.htm',
  '/info/1027/5210.htm',
  '/jqjjhdz/list.htm',
  '/kjrc/gjjcqnjjhdz_Al.htm',
  '/gjjcqnjjhdz.htm',
  '/gjjcqn/list.htm',
  '/yxxk/gjjcqn/list.htm',
  '/yxqn/list.htm',
  '/yxqxjjhdz/list.htm',
  '/yxqxjjhdz/list.htm',
  '/yxqxjjhdz/list1.htm',
  '/yxqxjjhdz/list2.htm',
  '/yxqnjjhdz/list.htm',
  '/yxqnjjhdz/list.htm',
  '/yxqnjjhdz/list1.htm',
  '/yxqnjjhdz/list2.htm',
]

export const UNIVERSITY_SUBDOMAINS = [
  'www',
  'ac',
  'rsrc',
  'hr',
  'rsc',
  'kfy',
  'kyy',
  'kyc',
  'life',
  'me',
  'ins',
  'news',
  'bio',
  'faculty',
  'lifesciences',
]
